packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^25.5.0
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  react: ^19.2.4
  react-dom: ^19.2.4
  tailwindcss: ^4.1.18
  typescript: 6.0.2

allowBuilds:
  electron: true
